### ISSUE TITLE
Deserialization failures when fetching index funds

### ISSUE THREAD

**Issue by samtay** [xemwebe/yahoo_finance_api#16]
Do you intend for your library to support fetching mutual funds in addition to stocks? It seems that yahoo doesn't report an `adjclose` for these:
```
Error when fetching FSKAX: DeserializeFailed("missing field `adjclose`")
Error when fetching FSPSX: DeserializeFailed("missing field `adjclose`")
Error when fetching FXAIX: DeserializeFailed("missing field `adjclose`")
Error when fetching FXNAX: DeserializeFailed("missing field `adjclose`")
Error when fetching VBTLX: DeserializeFailed("missing field `adjclose`")
Error when fetching VFIAX: DeserializeFailed("missing field `adjclose`")
Error when fetching VMCIX: DeserializeFailed("missing field `adjclose`")
Error when fetching VSCIX: DeserializeFailed("missing field `adjclose`")
Error when fetching VSMAX: DeserializeFailed("missing field `adjclose`")
Error when fetching VTSAX: DeserializeFailed("missing field `adjclose`")
Error when fetching VTSNX: DeserializeFailed("missing field `adjclose`")
```
Perhaps these can be made optional? I retrieved the VTI quote fine (the ETF version of VTSAX), so it does appear to be specific to mutual funds. I also noticed a deserialization failure when fetching a money market fund, although I actually didn't intend to do this, I'm not sure if you intend for this to be possible:
```
Error when fetching VMFXX: DeserializeFailed("missing field `volume`")
```

I just want to fetch the mutual funds though. Would you like to support this in your lib?

**Comment by samtay** [comment]
I cloned your lib to play with this, and noticed you have a test to enforce that BF.B throws this same exception, so I'm guessing you do not want to support this. In any case I started to hack it myself to investigate. After changing `high`, `volume`, `adjclose`, and then even `close` to optional fields, I put in some logging to see the difference between VTSAX and VTI. VTSAX doesn't get any of those arrays of pricing data:
```
Object({
    "chart": Object({
        "error": Null,
        "result": Array([Object({
            "indicators": Object({
                "adjclose": Array([Object({})]),
                "quote": Array([Object({})])
            }),
            "meta": Object({
                "chartPreviousClose": Number(109.64),
                "currency": String("USD"),
                "currentTradingPeriod": Object({
                    "post": Object({
                        "end": Number(1625616000),
                        "gmtoffset": Number(-14400),
                        "start": Number(1625601600),
                        "timezone": String("EDT")
                    }),
                    "pre": Object({
                        "end": Number(1625578200),
                        "gmtoffset": Number(-14400),
                        "start": Number(1625558400),
                        "timezone": String("EDT")
                    }),
                    "regular": Object({
                        "end": Number(1625601600),
                        "gmtoffset": Number(-14400),
                        "start": Number(1625578200),
                        "timezone": String("EDT")
                    })
                }),
                "dataGranularity": String("1d"),
                "exchangeName": String("NAS"),
                "exchangeTimezoneName": String("America/New_York"),
                "firstTradeDate": Number(974125800),
                "gmtoffset": Number(-14400),
                "instrumentType": String("MUTUALFUND"),
                "priceHint": Number(2),
                "range": String("1d"),
                "regularMarketPrice": Number(109.36),
                "regularMarketTime": Number(1625610533),
                "symbol": String("VTSAX"),
                "timezone": String("EDT"),
                "validRanges": Array([String("1mo"), String("3mo"), String("6mo"), String("ytd"), String("1y"), String("2y"), String("5y"), String("10y"), String("max")])
            })
        })])
    })
})
```
The only price fields are `regularMarketPrice` and `charPreviousClose`. So, I would think if you _did_ support this, the type might have to diverge from the current `Quote` struct, perhaps something like an enum of different quote types.

**Comment by xemwebe** [comment]
Thanks for highlighting this problem. Making all fields optional works, but leaves all the burden to the user of the library at would be not the best choice. It will also break existing code.

Adding a special interface for mutual funds might be a better alternative. Since it seems possible to identify the asset class from the meta data information, these could be combined with a method to interrogate the asset class up-front and maybe a helpful error message if the wrong method has been called to retrieve the data of a given instrument type. I will have a closer look at it.

**Comment by xemwebe** [comment]
I have just wrote a quick test to verify your observation - and failed (to verify). I.e. If I use get_quote_history, I do get back a valid list of quotes, including the field adjclose. Could you please specify which exact method fails for mutual funds?

**Comment by xemwebe** [comment]
Okay, the problem seems to be related to how the presumably latest quote is fetched - I'll have to investigate this a bit more.

**Comment by xemwebe** [comment]
I fixed a bug that caused a failure if the range of quote from which the latest quote is fetched contains only one quote. In addition, it seems that the yahoo API is somewhat incoherent in accepting sometimes an interval of 1 months as "1m", sometimes it has to be "1mo". However, if I try to get the latest quote for VTSAX by calling either `provider.get_latest_quote("VTSAX", "1d", "1m")` or `provider.get_latest_quote("VTSAX", "1d", "1d")` (in spite of the `1m` setting being apparently ignored by the API), where `provider` is of type `YahooConnector`, I do get a valid response in my test case.

Please let me know if this solves your issue.

**Comment by samtay** [comment]
Hey thanks for the quick turn around. This still doesn't work for me; in fact, your test fails locally for me:
```
❯ cargo test
   Compiling yahoo_finance_api v1.2.2 (/home/sam/code/yahoo_finance_api)
    Finished test [unoptimized + debuginfo] target(s) in 8.03s
     Running unittests (target/debug/deps/yahoo_finance_api-65d0631998b62523)

running 11 tests
test async_impl::tests::test_api_responses_missing_fields ... ok
test async_impl::tests::test_get ... ok
test async_impl::tests::test_get_quote_history ... ok
test async_impl::tests::test_get_quote_range ... ok
test async_impl::tests::test_large_volume ... ok
test async_impl::tests::test_mutual_fund_latest ... FAILED
test async_impl::tests::test_get_single_quote ... ok
test async_impl::tests::test_mutual_fund_history ... ok
test async_impl::tests::test_mutual_fund_range ... ok
test async_impl::tests::test_search_ticker ... ok
test async_impl::tests::test_strange_api_responses ... ok

failures:

---- async_impl::tests::test_mutual_fund_latest stdout ----
thread 'async_impl::tests::test_mutual_fund_latest' panicked at 'called `Result::unwrap()` on an `Err` value: DeserializeFailed("missing field `adjclose`")', src/async_impl.rs:210:88


failures:
    async_impl::tests::test_mutual_fund_latest

test result: FAILED. 10 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.77s

error: test failed, to rerun pass '--lib'
```

I already wrote a small wrapper for my purposes, so no rush, but I'm happy to provide any more information for you as you try to run this down.

**Comment by xemwebe** [comment]
Interesting. But at least the two other tests (test_mutual_fund_history and test_mutual_fund_range) pass. 

Apparently, sometimes (maybe depending on the day time), the last value in the series is just null. I have modified the algorithm again slightly, fetching the quotes from the last month and returning the latest valid quote from that list (the code should have done this anyway, but didn't due to some interchanged variables). 

Could you please confirm whether that works for you?

**Comment by samtay** [comment]
Your test suite now passes locally for me, _but_ usage fails depending on the interval argument. I get consistent failures for `get_latest_quotes(mutual_fund_ticker, "1m")`, but this might be expected when requesting minute intervals for mutual funds updated daily? Perhaps the best we can do is a documentation comment.

When using "1d" as your tests do, the only failure for me now is the money market fund `VMFXX`. If you're interested in supporting it, this is a failing test:
```rust
#[test]
fn test_money_market_latest() {
    let provider = YahooConnector::new();
    let response = tokio_test::block_on(provider.get_latest_quotes("VMFXX", "1d")).unwrap();
    assert_eq!(&response.chart.result[0].meta.symbol, "VMFXX");
    assert_eq!(&response.chart.result[0].meta.range, "1mo");
    assert_eq!(&response.chart.result[0].meta.data_granularity, "1d");
    let _ = response.last_quote().unwrap();
}
```
The failure is due to missing `adjclose`
```
---- async_impl::tests::test_money_market_latest stdout ----
thread 'async_impl::tests::test_money_market_latest' panicked at 'called `Result::unwrap()` on an `Err` value: DeserializeFailed("missing field `adjclose`")', src/async_impl.rs:232:88
```

But, I don't see much reason to support `VMFXX`; from what I understand it will always have a price of $1. Feel free to close this as you see fit. And again, thanks for the quick turnaround!

**Comment by xemwebe** [comment]
Yes, I would expect mutual funds to fail consistently on a minute interval. Even for the most liquid stocks most of the entries will be empty. But it will certainly be a good idea to give a more detailed description of the parameters and which values are good choices. 

Regarding VMFXX, the failure is due a lack of support by yahoo. Regardless of the parameter setting,  no quotes are returned and you can't even get any infos if query it via the finance yahoo web site.

**Comment by xemwebe** [comment]
Since the issues seemed to be solved, I close this thread.
